name: Terraform Infrastructure
on:
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      - run: terraform -chdir=infra init
      - run: terraform -chdir=infra plan
